services:
  docs-serve:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: dassi0cl/docsserve:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./web:/app/web:ro
      - ./README.md:/app/demo/README.md
      - security-auth-access:/etc/nginx/security

volumes:
  security-auth-access: